name: Deploy VitePress site

on:
    push:
        branches:
            - main # 当 main 分支有推送时触发

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: npm

            - name: Install dependencies
              run: npm install

            - name: Build VitePress site
              run: npm run docs:build
              # 假设你在 package.json 中定义了 "docs:build": "vitepress build docs"

            - name: Add .nojekyll
              run: touch .vitepress/dist/.nojekyll

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .vitepress/dist
